# Use root/example as user/password credentialsx

services:

  node-red:
    container_name: se4as-project-node-red
    build:
      context: ./monitor/nodered/
      dockerfile: Dockerfile
    image: nodered:latest
    env_file:
      - .env
    ports:
      - "1880:1880"
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.100
    volumes:
      - $PWD/monitor/nodered/data:/data
    depends_on:
      - mosquitto

  mosquitto:
    container_name: se4as-project-mosquitto
    image: eclipse-mosquitto
    volumes:
      - $PWD/broker/mosquitto/config:/mosquitto/config
      - $PWD/broker/mosquitto/log:/mosquitto/log
      - $PWD/broker/mosquitto/data/:/mosquitto/data
    restart: always
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.101
    ports:
      - "1883:1883"

  influxdb:
    container_name: se4as-project-influxdb
    image: influxdb:2.7.4
    env_file:
      - .env
    volumes:
    - $PWD/knowledge/influxdb/data:/var/lib/influxdb2:rw
    - $PWD/knowledge/influxdb/config:/etc/influxdb2:rw
    ports:
       - "8086:8086"
    networks:
       se4as-project-network:
         ipv4_address: 172.30.0.103

  telegraf:
    restart: always
    container_name: se4as-project-telegraf
    image: telegraf:latest
    env_file:
      - .env
    volumes:
      - $PWD/knowledge/telegraf/mqtt_client.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.104

  grafana:
    restart: always
    image: grafana/grafana-oss:latest
    container_name: se4as-project-grafana
    volumes:
      - $PWD/monitor/grafana/data:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.105

  sensor:
    container_name: se4as-project-sensors
    build:
      context: ./monitor/sensors/
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.106

  actuator:
    container_name: se4as-project-actuator
    build:
      context: ./executors/actuators/
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.107

  executor:
    container_name: se4as-project-executor
    build:
      context: ./executors/
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.108

  planner:
    container_name: se4as-project-planner
    build:
      context: ./planner/
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.109

  analyzer:
    container_name: se4as-project-analyzer
    build:
      context: ./analyzer/
      dockerfile: Dockerfile
    depends_on:
      - mosquitto
    networks:
      se4as-project-network:
        ipv4_address: 172.30.0.110

networks:
  se4as-project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16