from enum import StrEnum


class JsonProperties(StrEnum):
    SENSORS_ROOT='sensors',
    ACTUATORS_ROOT='actuators',
    ACTUATORS_CATEGORIES_ROOT='categories',
    STATE_ROOT='states',
    CONFIGURATION_ROOT='configuration',
    TEMPERATURE='temperature',
    MIN_TEMPERATURE='min_temp',
    WORKING_THRESHOLD='working_threshold',
    LIGHT='light',
    ENERGY='energy',
    TOTAL_KW='total_kw',
    SMART_APPLIANCE='smart_appliance',
    LIGHT_LAMPS='lamps',
    WINDOWS='windows',
    SHUTTERS='shutters',
    ROOM='room',
    STARTING_VALUE='starting_value',
    LUX_PER_LAMP='lux_per_lamp',
    LUX_FROM_SUN='lux_from_sun',
    DATA_TYPE='data_type',
    SINGLE_VALUE='value',
    MULTIPLE_VALUES='values',
    VALUE_DELTA_RANGE='delta_range',
    VALUE_LOWER_LIMIT='lower_limit',
    VALUE_UPPER_LIMIT='upper_limit',
    VALUE_UPPER_CORRECTION='upper_limit_correction',
    VALUE_LOWER_CORRECTION='lower_limit_correction',
    STATE_TYPE='state_type',
    STATE_VALUE='state',
    AUTOMATION_TOGGLE_VALUE='automation_enabled',
    SMART_FRIDGE_LOAD='load',
    SMART_FRIDGE_TEMPERATURE='temp',
    SMART_FRIDGE_THRESHOLD='refill_threshold',
    SMART_FRIDGE_OPEN_DELTA_RANGE='open_delta_range',
    SMART_FRIDGE_REFILL_DELTA_RANGE='refill_delta_range',
    INFLUX_VALUE='_value',
    INFLUX_MEASUREMENT='_measurement',
    PLANNER_DISHWASHER_SWITCH='dishwashers',
    PLANNER_FRIDGE_SWITCH='fridges',
    PLANNER_LAMPS_SWITCH= 'lamps',
    PLANNER_THERMOSTAT_SWITCH='thermostats'

